apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: jeevan-namespace-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - patch
  - update
  - create
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update 
