apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: jeevan-namespace-clusterrole-binding
 namespace: default
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: jeevan-namespace-cluster-service-account
roleRef:
 kind: Role
 apiGroup: ""
 name: jeevan-namespace-clusterrole
