# permissions for end users to view netscouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netscout-viewer-role
rules:
- apiGroups:
  - core.savjee.com
  resources:
  - netscouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.savjee.com
  resources:
  - netscouts/status
  verbs:
  - get
