apiVersion: v1
kind: Service
metadata:
 name: rest-api-server-service
 namespace: jeevan-namespace
spec:
 selector:
  app: rest-api-server
 ports:
 - name: https
   port: {{ .Values.rest_api_server.service.port }}
