apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: jeevan-namespace-role-binding
 namespace: jeevan-namespace
subjects:
- kind: ServiceAccount
  apiGroup: ""
  name: jeevan-namespace-service-account
roleRef:
 kind: Role
 apiGroup: ""
 name: jeevan-namespace-role
