apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: shell-client
 namespace: jeevan-namespace
spec:
 selector:
  matchLabels:
   app: shell-client
 template:
  metadata:
   labels:
    app: shell-client
  spec:
   containers:
   - name: shell-client1
     image: 10.20.52.114:5000/shell-client1
     securityContext:
      privileged: true
     volumeMounts:
     - name: host-proc
       mountPath: /root/proc
   - name: shell-client2
     image: 10.20.52.114:5000/shell-client2
     securityContext:
      privileged: true
   volumes:
   - name: host-proc
     hostPath:
      path: /proc
